[build]
builder = "NIXPACKS"

[deploy]
buildCommand = "npm run build"
preDeployCommand = "npm run db:push"
startCommand = "npm run start:standalone"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
