import assert from "node:assert/strict";
import test from "node:test";
import { randomInt, randomUUID } from "node:crypto";
import { registerHooks } from "node:module";
import { setTimeout as delay } from "node:timers/promises";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { blacklistSchemaStatements } from "../scripts/document-blacklist-schema.mjs";
import { store } from "./document-blacklist-test-loader.mjs";

const connectionString = process.env.BLACKLIST_TEST_DATABASE_URL;

test("PostgreSQL real: migracion, auditoria, idempotencia y carreras de bloqueo", { skip: !connectionString }, async (t) => {
  const url = new URL(connectionString);
  assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(url.hostname), "Las pruebas sólo pueden ejecutarse contra localhost");
  assert.match(url.pathname, /^\/blacklist_test(?:_[a-z0-9]+)?$/, "Se requiere una base aislada blacklist_test");
  const pool = new pg.Pool({ connectionString });
  // The generated Next.js client uses extensionless TS imports; resolve only its
  // local generated modules for this direct Node test (never rewrite production).
  const hooks = registerHooks({ resolve(specifier, context, nextResolve) {
    if (specifier.startsWith(".") && context.parentURL?.includes("/app/generated/prisma/")) {
      try { return nextResolve(specifier, context); } catch (error) {
        if (error.code === "ERR_MODULE_NOT_FOUND") return nextResolve(`${specifier}.ts`, context);
        throw error;
      }
    }
    return nextResolve(specifier, context);
  } });
  const { PrismaClient } = await import("../app/generated/prisma/client.ts");
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
  const actor = { id: 991001, nombre: "Administrador sintético de pruebas" };
  const document = () => `9${String(randomInt(0, 1_000_000_000)).padStart(12, "0")}`;
  const create = (doc, mutationId = randomUUID()) => store.parseBlacklistMutation("POST", { documento: doc, motivo: "Bloqueo sintético de prueba", mutationId });
  const mutate = (input, who = actor) => prisma.$transaction((tx) => store.mutateBlacklist(tx, input, who), { timeout: 15000 });
  const deferred = () => { let resolve; const promise = new Promise((done) => { resolve = done; }); return { promise, resolve }; };
  async function waitForAdvisoryWaiter() {
    for (let i = 0; i < 100; i++) {
      const result = await pool.query("SELECT count(*)::int AS n FROM pg_stat_activity WHERE datname = current_database() AND wait_event = 'advisory'");
      if (result.rows[0].n > 0) return;
      await delay(20);
    }
    assert.fail("La segunda transacción no esperó el lock del documento");
  }
  try {
    // Serialize fixture DDL with the bulk suite, just as production predeploy does.
    const setup = await pool.connect();
    try {
      await setup.query("BEGIN");
      await setup.query("SELECT pg_advisory_xact_lock(hashtext('blacklist-test-schema-setup'))");
      await setup.query('CREATE TABLE IF NOT EXISTS public."Usuario" ("id" INTEGER PRIMARY KEY)');
      await setup.query('CREATE TABLE IF NOT EXISTS public."Venta" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');
      await setup.query('INSERT INTO public."Usuario" ("id") VALUES ($1), ($2) ON CONFLICT DO NOTHING', [actor.id, actor.id + 1]);
      for (let run = 0; run < 2; run++) for (const statement of blacklistSchemaStatements) await setup.query(statement);
      await setup.query("COMMIT");
    } catch (error) {
      await setup.query("ROLLBACK");
      throw error;
    } finally {
      setup.release();
    }

    await t.test("schema se puede reejecutar y guardia real PrismaPg no deserializa lock void", async () => {
      await prisma.$transaction((tx) => store.assertDocumentAllowed(document(), tx, true));
      const result = await pool.query("SELECT data_type FROM information_schema.columns WHERE table_name='Venta' AND column_name='clienteDocumento'");
      assert.equal(result.rows[0].data_type, "text");
    });

    await t.test("crear, duplicado normalizado, replay y autor vinculado con auditoria única", async () => {
      const doc = document();
      const input = create(doc);
      const first = await mutate(input);
      assert.equal(first.item.documento, doc);
      assert.equal(first.item.version, 1);
      assert.equal(first.item.activa, true);
      assert.equal((await mutate(input)).idempotent, true);
      await assert.rejects(mutate(create(`00${doc}`)), { code: "ALREADY_BLACKLISTED", status: 409 });
      await assert.rejects(mutate(input, { ...actor, id: actor.id + 1 }), { code: "MUTATION_CONFLICT" });
      await assert.rejects(mutate({ ...input, motivo: "Motivo diferente" }), { code: "MUTATION_CONFLICT" });
      const audit = await pool.query('SELECT * FROM public."ListaNegraDocumentoEvento" WHERE "registroId"=$1', [first.item.id]);
      assert.equal(audit.rowCount, 1);
      assert.equal(audit.rows[0].before, null);
      assert.equal(audit.rows[0].after.documento, doc);
      assert.equal(audit.rows[0].actorUserId, actor.id);
      await assert.rejects(pool.query('UPDATE public."ListaNegraDocumentoEvento" SET "motivo"=$1 WHERE "registroId"=$2', ["Cambio indebido", first.item.id]), /append-only/);
      await assert.rejects(pool.query('DELETE FROM public."ListaNegraDocumentoEvento" WHERE "registroId"=$1', [first.item.id]), /append-only/);
    });

    await t.test("desbloquear requiere version vigente; reactivar conserva identidad e historial", async () => {
      const first = await mutate(create(document()));
      const update = store.parseBlacklistMutation("PATCH", { id: first.item.id, activa: false, motivo: "Desbloqueo sintético", version: 1, mutationId: randomUUID() });
      const second = await mutate(update);
      assert.equal(second.item.version, 2);
      assert.equal(second.item.activa, false);
      await store.assertDocumentAllowed(second.item.documento, prisma);
      await assert.rejects(mutate({ ...update, mutationId: randomUUID() }), { code: "VERSION_CONFLICT" });
      const third = await mutate(create(first.item.documento));
      assert.equal(third.item.id, first.item.id);
      assert.equal(third.item.version, 3);
      await assert.rejects(store.assertDocumentAllowed(third.item.documento, prisma), { code: "DOCUMENT_BLACKLISTED" });
      const audit = await pool.query('SELECT "before", "after" FROM public."ListaNegraDocumentoEvento" WHERE "registroId"=$1 ORDER BY "createdAt"', [first.item.id]);
      assert.equal(audit.rowCount, 3);
      assert.equal(audit.rows[1].before.motivo, first.item.motivo);
      assert.equal(audit.rows[1].after.activa, false);
    });

    await t.test("dos altas simultaneas no duplican cedula ni auditoria", async () => {
      const doc = document();
      const results = await Promise.allSettled([mutate(create(doc)), mutate(create(doc))]);
      assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
      assert.equal(results.find((result) => result.status === "rejected").reason.code, "ALREADY_BLACKLISTED");
      const audit = await pool.query('SELECT count(*)::int AS n FROM public."ListaNegraDocumentoEvento" e JOIN public."ListaNegraDocumento" d ON d."id"=e."registroId" WHERE d."documento"=$1', [doc]);
      assert.equal(audit.rows[0].n, 1);
    });

    await t.test("si falla auditoria se revierte el bloqueo completo sin dejar alta parcial", async () => {
      const doc = document();
      await assert.rejects(prisma.$transaction(async (tx) => store.mutateBlacklist({
        $queryRawUnsafe: (sql, ...args) => tx.$queryRawUnsafe(sql, ...args),
        $executeRawUnsafe: (sql, ...args) => {
          if (sql.includes('INSERT INTO public."ListaNegraDocumentoEvento"')) throw new Error("Fallo de auditoría sintético");
          return tx.$executeRawUnsafe(sql, ...args);
        },
      }, create(doc), actor)), /Fallo de auditoría sintético/);
      assert.equal((await pool.query('SELECT count(*)::int AS n FROM public."ListaNegraDocumento" WHERE "documento"=$1', [doc])).rows[0].n, 0);
    });

    await t.test("si el bloqueo gana la carrera la venta espera y no se inserta", async () => {
      const doc = document();
      const locked = deferred();
      const release = deferred();
      const activation = prisma.$transaction(async (tx) => {
        const result = await store.mutateBlacklist(tx, create(doc), actor);
        locked.resolve();
        await release.promise;
        return result;
      }, { timeout: 15000 });
      await locked.promise;
      const sale = prisma.$transaction(async (tx) => {
        await store.assertDocumentAllowed(doc, tx, true);
        return tx.$executeRawUnsafe('INSERT INTO public."Venta" ("clienteDocumento") VALUES ($1)', doc);
      }, { timeout: 15000 });
      // Attach rejection before releasing to avoid an unhandled-rejection race.
      const rejected = assert.rejects(sale, { code: "DOCUMENT_BLACKLISTED" });
      try { await waitForAdvisoryWaiter(); } finally { release.resolve(); }
      await activation;
      await rejected;
      assert.equal((await pool.query('SELECT count(*)::int AS n FROM public."Venta" WHERE "clienteDocumento"=$1', [doc])).rows[0].n, 0);
    });

    await t.test("si una venta ya tiene lock termina antes de activar; despues se rechazan nuevas", async () => {
      const doc = document();
      const locked = deferred();
      const release = deferred();
      const sale = prisma.$transaction(async (tx) => {
        await store.assertDocumentAllowed(doc, tx, true);
        locked.resolve();
        await release.promise;
        return tx.$executeRawUnsafe('INSERT INTO public."Venta" ("clienteDocumento") VALUES ($1)', doc);
      }, { timeout: 15000 });
      await locked.promise;
      const activation = mutate(create(doc));
      try { await waitForAdvisoryWaiter(); } finally { release.resolve(); }
      await sale;
      await activation;
      await assert.rejects(prisma.$transaction((tx) => store.assertDocumentAllowed(doc, tx, true)), { code: "DOCUMENT_BLACKLISTED" });
      assert.equal((await pool.query('SELECT count(*)::int AS n FROM public."Venta" WHERE "clienteDocumento"=$1', [doc])).rows[0].n, 1);
    });

    await t.test("listado filtra estado y cedula, responde sin campos internos de auditoria", async () => {
      const row = await mutate(create(document()));
      const result = await store.listBlacklist(prisma, { q: row.item.documento, estado: "ACTIVA", page: 1 });
      assert.equal(result.total, 1);
      assert.equal(result.items[0].id, row.item.id);
      assert.equal("createdByUserId" in result.items[0], false);
      assert.equal("requestHash" in result.items[0], false);
      assert.equal((await store.listBlacklist(prisma, { q: row.item.documento, estado: "INACTIVA", page: 1 })).total, 0);
    });
  } finally {
    await prisma.$disconnect();
    await pool.end();
    hooks.deregister();
  }
});
