import assert from "node:assert/strict";
import test from "node:test";
import { randomInt, randomUUID } from "node:crypto";
import { registerHooks } from "node:module";
import { setTimeout as delay } from "node:timers/promises";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { blacklistSchemaStatements } from "../scripts/document-blacklist-schema.mjs";
import { core, store, loadBlacklistModule } from "./document-blacklist-test-loader.mjs";

const bulkCore = loadBlacklistModule("lib/document-blacklist-bulk-core.ts", { "@/lib/document-blacklist-core": core });
const bulk = loadBlacklistModule("lib/document-blacklist-bulk-store.ts", {
  "@/lib/document-blacklist-core": core,
  "@/lib/document-blacklist-bulk-core": bulkCore,
});
const connectionString = process.env.BLACKLIST_TEST_DATABASE_URL;

test("PostgreSQL real: carga masiva atomica, snapshot, limites y concurrencia", { skip: !connectionString }, async (t) => {
  const url = new URL(connectionString);
  assert.ok(["localhost", "127.0.0.1", "[::1]"].includes(url.hostname));
  assert.match(url.pathname, /^\/blacklist_test(?:_[a-z0-9]+)?$/);
  const hooks = registerHooks({ resolve(specifier, context, nextResolve) {
    if (specifier.startsWith(".") && context.parentURL?.includes("/app/generated/prisma/")) {
      try { return nextResolve(specifier, context); } catch (error) {
        if (error.code === "ERR_MODULE_NOT_FOUND") return nextResolve(`${specifier}.ts`, context);
        throw error;
      }
    }
    return nextResolve(specifier, context);
  } });
  const { PrismaClient } = await import("../app/generated/prisma/client.ts");
  const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
  const pool = new pg.Pool({ connectionString });
  const actor = { id: 992001, nombre: "Administrador masivo sintético" };
  const doc = () => `8${String(randomInt(0, 1_000_000_000)).padStart(12, "0")}`;
  const single = (input) => prisma.$transaction((tx) => store.mutateBlacklist(tx, input, actor));
  const create = (documento) => single(store.parseBlacklistMutation("POST", { documento, motivo: "Motivo individual original", mutationId: randomUUID() }));
  const deactivate = (item) => single(store.parseBlacklistMutation("PATCH", { id: item.id, version: item.version, activa: false, motivo: "Desactivación sintética posterior", mutationId: randomUUID() }));
  const parse = (texto, motivo = "Motivo común de prueba masiva") => bulkCore.parseBlacklistBulkInput({ texto, motivo });
  const preview = (input, who = actor) => bulk.previewBlacklistBulk(prisma, input, who);
  const commitInput = (input, view, mutationId = randomUUID()) => bulk.parseBlacklistBulkCommit({ texto: input.texto, motivo: input.motivo, fingerprint: view.fingerprint, mutationId, confirmed: true });
  const commit = (input, who = actor) => prisma.$transaction((tx) => bulk.commitBlacklistBulk(tx, input, who), { timeout: 45000 });
  const getItem = async (documento) => (await prisma.$queryRawUnsafe('SELECT * FROM public."ListaNegraDocumento" WHERE "documento"=$1', documento))[0];
  const auditCount = async (documento) => (await pool.query('SELECT count(*)::int AS n FROM public."ListaNegraDocumentoEvento" e JOIN public."ListaNegraDocumento" d ON e."registroId"=d."id" WHERE d."documento"=$1', [documento])).rows[0].n;
  const receiptCount = async (id) => (await pool.query('SELECT count(*)::int AS n FROM public."ListaNegraImportacion" WHERE "id"=$1', [id])).rows[0].n;

  try {
    const setup = await pool.connect();
    try {
      await setup.query("BEGIN");
      await setup.query("SELECT pg_advisory_xact_lock(hashtext('blacklist-test-schema-setup'))");
      await setup.query('CREATE TABLE IF NOT EXISTS public."Usuario" ("id" INTEGER PRIMARY KEY)');
      await setup.query('CREATE TABLE IF NOT EXISTS public."Venta" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');
      await setup.query('INSERT INTO public."Usuario" ("id") VALUES ($1), ($2) ON CONFLICT DO NOTHING', [actor.id, actor.id + 1]);
      for (let run = 0; run < 2; run++) for (const statement of blacklistSchemaStatements) await setup.query(statement);
      await setup.query("COMMIT");
    } catch (error) {
      await setup.query("ROLLBACK");
      throw error;
    } finally { setup.release(); }

    await t.test("preview distingue nuevas, reactivar, activas, duplicadas e invalidas sin escribir", async () => {
      const active = await create(doc());
      const inactive = await deactivate((await create(doc())).item);
      const fresh = doc();
      const input = parse([fresh, active.item.documento, inactive.item.documento, `00${fresh}`, "1e9"].join("\n"));
      const view = await preview(input);
      assert.deepEqual({ ...view.summary }, { total: 5, nuevas: 1, reactivar: 1, yaBloqueadas: 1, duplicadas: 1, invalidas: 1 });
      assert.equal(view.canConfirm, false);
      assert.equal(view.fingerprint, (await preview(input)).fingerprint);
      assert.equal(await getItem(fresh), undefined);
      assert.equal(await auditCount(active.item.documento), 1);
      assert.equal(await auditCount(inactive.item.documento), 2);
      const submission = commitInput(input, view);
      await assert.rejects(commit(submission), { code: "BULK_INVALID_ROWS" });
      assert.equal(await receiptCount(submission.mutationId), 0);
      assert.equal(await getItem(fresh), undefined);
    });

    await t.test("lote mixto omite activas y duplicadas sin modificar motivos ni historial anterior", async () => {
      const active = (await create(doc())).item;
      const inactive = (await deactivate((await create(doc())).item)).item;
      const originalActive = await getItem(active.documento);
      const fresh = doc();
      const input = parse(`${fresh}\n${active.documento}\n${inactive.documento}\n00${fresh}`);
      const view = await preview(input);
      const result = await commit(commitInput(input, view));
      assert.deepEqual({ ...result.summary }, { total: 4, nuevas: 1, reactivar: 1, yaBloqueadas: 1, duplicadas: 1, invalidas: 0 });
      assert.equal(result.items.length, 3);
      assert.equal(result.actorName, actor.nombre);
      assert.equal((await getItem(inactive.documento)).version, 3);
      assert.equal((await getItem(inactive.documento)).motivo, input.motivo);
      assert.deepEqual(await getItem(active.documento), originalActive);
      assert.equal(await auditCount(active.documento), 1);
      assert.equal(await auditCount(inactive.documento), 3);
      assert.equal(await auditCount(fresh), 1);
      const audits = await pool.query('SELECT "before","after","actorUserId" FROM public."ListaNegraDocumentoEvento" WHERE "registroId"=$1 ORDER BY "createdAt"', [inactive.id]);
      assert.equal(audits.rows[2].before.activa, false);
      assert.equal(audits.rows[2].before.motivo, inactive.motivo);
      assert.equal(audits.rows[2].after.activa, true);
      assert.equal(audits.rows[2].actorUserId, actor.id);
      await assert.rejects(store.assertDocumentAllowed(fresh, prisma), { code: "DOCUMENT_BLACKLISTED" });
      await assert.rejects(pool.query('UPDATE public."ListaNegraImportacion" SET "motivo"=$1 WHERE "id"=$2', ["Cambio indebido", result.importId]), /append-only/);
      await assert.rejects(pool.query('DELETE FROM public."ListaNegraImportacion" WHERE "id"=$1', [result.importId]), /append-only/);
    });

    await t.test("reintento exacto recupera recibo y no reactiva cedulas desactivadas después", async () => {
      const fresh = doc();
      const input = parse(fresh);
      const submission = commitInput(input, await preview(input));
      const first = await commit(submission);
      await deactivate(await getItem(fresh));
      const replay = await commit(submission);
      assert.equal(replay.idempotent, true);
      assert.equal(replay.createdAt, first.createdAt);
      assert.equal((await getItem(fresh)).activa, false);
      assert.equal(await auditCount(fresh), 2);
      assert.equal(await receiptCount(submission.mutationId), 1);
      await assert.rejects(commit({ ...submission, motivo: "Otro motivo diferente" }), { code: "MUTATION_CONFLICT" });
      await assert.rejects(commit(submission, { ...actor, id: actor.id + 1 }), { code: "MUTATION_CONFLICT" });
    });

    await t.test("cambio posterior a preview exige revisar de nuevo sin guardar parte del lote", async () => {
      const changed = doc();
      const untouched = doc();
      const input = parse(`${changed}\n${untouched}`);
      const submission = commitInput(input, await preview(input));
      await create(changed);
      await assert.rejects(commit(submission), { code: "BULK_PREVIEW_CHANGED", status: 409 });
      assert.equal(await getItem(untouched), undefined);
      assert.equal(await receiptCount(submission.mutationId), 0);
      const activeInput = parse(changed);
      const activePreview = await preview(activeInput);
      assert.equal(activePreview.canConfirm, false);
      await assert.rejects(commit(commitInput(activeInput, activePreview)), { code: "BULK_NOTHING_TO_IMPORT" });
    });

    await t.test("rollback revierte todos los registros si falla auditoria o recibo", async () => {
      for (const failingTable of ["ListaNegraDocumentoEvento", "ListaNegraImportacion"]) {
        const documentos = [doc(), doc()];
        const input = parse(documentos.join("\n"));
        const submission = commitInput(input, await preview(input));
        await assert.rejects(prisma.$transaction((tx) => bulk.commitBlacklistBulk({
          $queryRawUnsafe: (sql, ...args) => tx.$queryRawUnsafe(sql, ...args),
          $executeRawUnsafe: (sql, ...args) => {
            if (sql.includes(`INSERT INTO public."${failingTable}"`)) throw new Error("Fallo sintético");
            return tx.$executeRawUnsafe(sql, ...args);
          },
        }, submission, actor)), { code: "DOCUMENT_BLACKLIST_UNAVAILABLE", status: 503 });
        for (const documento of documentos) assert.equal(await getItem(documento), undefined);
        assert.equal(await receiptCount(submission.mutationId), 0);
      }
    });

    await t.test("dos envios concurrentes del mismo lote tienen un solo recibo y auditoria", async () => {
      const fresh = doc();
      const input = parse(fresh);
      const submission = commitInput(input, await preview(input));
      const result = await Promise.all([commit(submission), commit(submission)]);
      assert.deepEqual(result.map((row) => row.idempotent).sort(), [false, true]);
      assert.equal(await auditCount(fresh), 1);
      assert.equal(await receiptCount(submission.mutationId), 1);
    });

    await t.test("lotes solapados se serializan y el segundo detecta su preview obsoleta", async () => {
      const documentos = [doc(), doc()];
      const input = parse(documentos.join("\n"));
      const view = await preview(input);
      const results = await Promise.allSettled([commit(commitInput(input, view)), commit(commitInput(input, view))]);
      assert.equal(results.filter((result) => result.status === "fulfilled").length, 1);
      assert.equal(results.find((result) => result.status === "rejected").reason.code, "BULK_PREVIEW_CHANGED");
      for (const documento of documentos) assert.equal(await auditCount(documento), 1);
    });

    await t.test("adquiere locks en orden lexical aunque la lista venga al reves y comparte locks individuales", async () => {
      const documentos = [doc(), doc()].sort();
      const input = parse([...documentos].reverse().join("\n"));
      const submission = commitInput(input, await preview(input));
      const holder = await pool.connect();
      const probe = await pool.connect();
      let pending;
      try {
        await holder.query("BEGIN");
        await holder.query("SELECT pg_advisory_xact_lock(hashtext($1))", [`DOCUMENT_BLACKLIST:${documentos[1]}`]);
        pending = commit(submission);
        let hasFirstLock = false;
        for (let attempt = 0; attempt < 100 && !hasFirstLock; attempt++) {
          await probe.query("BEGIN");
          const check = await probe.query("SELECT pg_try_advisory_xact_lock(hashtext($1)) AS acquired", [`DOCUMENT_BLACKLIST:${documentos[0]}`]);
          hasFirstLock = !check.rows[0].acquired;
          await probe.query("ROLLBACK");
          if (!hasFirstLock) await delay(20);
        }
        assert.equal(hasFirstLock, true, "El lote debe adquirir la primera CC antes de esperar la segunda");
        assert.equal(await getItem(documentos[0]), undefined, "No debe escribir antes de tener todos los locks");
      } finally {
        await holder.query("ROLLBACK");
        holder.release();
        probe.release();
        if (pending) await pending;
      }
      for (const documento of documentos) await assert.rejects(store.assertDocumentAllowed(documento, prisma), { code: "DOCUMENT_BLACKLISTED" });
    });

    await t.test("acepta500 entradas y audita cada cedula una sola vez con guardia Prisma real", async () => {
      const prefix = `7${String(randomInt(100_000, 999_999))}`;
      const documentos = Array.from({ length: 500 }, (_, index) => `${prefix}${String(index).padStart(5, "0")}`);
      const input = parse(documentos.join("\n"));
      const view = await preview(input);
      assert.equal(view.summary.nuevas, 500);
      const startedAt = Date.now();
      const result = await commit(commitInput(input, view));
      t.diagnostic(`Lote500 guardado en ${Date.now() - startedAt}ms en PostgreSQL local.`);
      assert.equal(result.items.length, 500);
      assert.equal(result.summary.nuevas, 500);
      assert.equal(await receiptCount(result.importId), 1);
      const audit = await pool.query('SELECT count(*)::int AS n FROM public."ListaNegraDocumentoEvento" e JOIN public."ListaNegraDocumento" d ON d."id"=e."registroId" WHERE d."documento"=ANY($1::text[])', [documentos]);
      assert.equal(audit.rows[0].n, 500);
    });
  } finally {
    await prisma.$disconnect();
    await pool.end();
    hooks.deregister();
  }
});
