import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import test from 'node:test';import ts from 'typescript';import {createRequire} from 'node:module';import {createJiti} from 'jiti';
const root=process.cwd(),require=createRequire(import.meta.url),jiti=createJiti(import.meta.url,{alias:{'@':root}});const{buildCreditPaymentPlan}=await jiti.import('../lib/credit-payment-plan.ts');
class FixedDate extends Date{constructor(...args){super(...(args.length?args:["2026-10-07T15:00:00Z"]));}static now(){return new Date("2026-10-07T15:00:00Z").getTime();}}
const source=ts.transpileModule(fs.readFileSync(path.join(root,'app/dashboard/reportes/page.tsx'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;
async function render(role='central',params={}){const calls={};const sedes=role==='supervisor'?[{id:10,nombre:'Sede autorizada'}]:[{id:10,nombre:'Sede autorizada'},{id:20,nombre:'Otra sede'}];const credits=[{id:1,estado:'ACTIVO',montoCredito:3045588356.19,valorCuota:3045588356.19,plazoMeses:1,frecuenciaPago:'MENSUAL',fechaPrimerPago:new Date('2026-12-01T05:00:00Z'),fechaProximoPago:null,planCapitalVigente:null,pazYSalvoEmitidoAt:null},{id:2,estado:'ANULADO',montoCredito:100,valorCuota:100,plazoMeses:1}];const db={sede:{findMany:async q=>(calls.sedes=q,sedes)},credito:{findMany:async q=>(calls.credits=q,credits)},creditoAbono:{groupBy:async q=>(calls.paid=q,[]),aggregate:async q=>(calls.collected=q,{_sum:{valor:71778053.12345}})}};const mod={exports:{}};const mocks={'@/lib/prisma':{default:db},'@/lib/dashboard-access':{requireAdminOrSupervisorDashboardAccess:async()=>({admin:role!=='supervisor',session:{nombre:'Usuario conectado',rolNombre:role==='supervisor'?'Supervisor':'Administrador',aliadoAccesoCodigo:role==='central'?'FINSERPAY':'ALIADO',aliadoAccesoId:5,sedeId:10}})},'@/lib/aliados':{isFinserPayCentralAlly:code=>code==='FINSERPAY'},'@/lib/credit-payment-plan':{buildCreditPaymentPlan},'@/app/dashboard/_components/finser-navigation':{default:'Navigation'},'./report-center':{default:'Center'},'./report-center.module.css':{default:{}}};vm.runInNewContext(source,{exports:mod.exports,module:mod,require:name=>mocks[name]||require(name),Intl,URLSearchParams,Date:FixedDate,Map});const tree=await mod.exports.default({searchParams:Promise.resolve(params)});return{calls,props:tree.props.children[1].props.children.props,nav:tree.props.children[0].props};}
test('importes completos, acumulados y enlaces del período, sin alterar el plan de pagos',async()=>{const{props,calls,nav}=await render('central',{sedeId:'20',period:'previous-month'});assert.equal(props.reports.length,6);assert.equal(props.metrics.activeCredits,'1');assert.match(props.metrics.collected,/71\.778\.053,12345/);assert.match(props.metrics.portfolioBalance,/3\.045\.588\.356,19/);assert.equal(props.metrics.mora,'0%');assert.equal(nav.nombreUsuario,'Usuario conectado');assert.deepEqual(JSON.parse(JSON.stringify(calls.credits.where.sedeId)),{in:[20]});assert.equal(calls.credits.where.fechaCreacion,undefined);assert.ok(calls.collected.where.fechaAbono.gte);for(const r of props.reports){if(['credits','payments'].includes(r.kind)){assert.match(r.href,/from=/);assert.match(r.href,/to=/);assert.match(r.href,/sedeId=20/);}else assert.ok(!r.href.includes('?'));}});
test('permisos y sede no autorizada mantienen el alcance',async()=>{const ally=await render('ally',{sedeId:'999'});assert.equal(ally.props.reports.length,5);assert.equal(ally.calls.sedes.where.aliadoId,5);assert.equal(ally.props.selectedSedeId,'');assert.deepEqual(JSON.parse(JSON.stringify(ally.calls.credits.where.sedeId)),{in:[10,20]});const supervisor=await render('supervisor');assert.equal(supervisor.props.reports.length,2);assert.equal(supervisor.calls.sedes.where.id,10);assert.deepEqual(JSON.parse(JSON.stringify(supervisor.calls.credits.where.sedeId)),{in:[10]});});
test('todo el historial no impone fechas ni filtros de plataforma inexistentes',async()=>{const{props,calls}=await render('central',{period:'all'});assert.equal(calls.collected.where.fechaAbono,undefined);assert.ok(props.reports.every(r=>!r.href.includes('?')));});
if(process.env.REPORT_CENTER_QA_OUTPUT){fs.writeFileSync(process.env.REPORT_CENTER_QA_OUTPUT,JSON.stringify((await render()).props));}
