"use client";
import { useState } from "react";
import { Button, Card, DataTable } from "@/app/_components/finser-ui";
import type { HistoricalSource } from "@/lib/credit-historical-reconciliation";
type Preview={previewHash:string;cliente:string;documento:string;folio:string;abonosAnteriores:{id:number;valor:number;fecha:string}[];abonosNuevos:HistoricalSource["abonos"];saldoCapital:number;saldoPendiente:number;fuente:string;cuotas:{numero:number;fechaVencimiento:string;valorProgramado:number;valorAbonadoAlCorte:number;saldoCapital:number}[];aplicado?:boolean};
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(n);
export default function ReconciliationForm({id}:{id:number}) {
 const [source,setSource]=useState<HistoricalSource|null>(null),[preview,setPreview]=useState<Preview|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[checked,setChecked]=useState(false);
 async function submit(confirm=false) {
  setBusy(true);setError("");try {
   const r=await fetch(`/api/creditos/${id}/conciliacion-historica`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source,accion:confirm?"CONFIRMAR":"PREVISUALIZAR",previewHash:confirm?preview?.previewHash:undefined})});
   const body=await r.json();if(!r.ok) throw new Error(body.error||"No se pudo conciliar.");setPreview(body);
  }catch(e){setError(e instanceof Error?e.message:"No se pudo conciliar.");}finally{setBusy(false);}
 }
 return <><Card className="grid gap-4 p-5"><p>Esta corrección sustituye el historial importado, conserva los originales anulados y registra una revisión inmutable. No recibe dinero nuevo ni modifica los documentos contractuales firmados.</p><label className="grid gap-2 font-semibold">Archivo de conciliación documental (JSON)<input aria-label="Archivo de conciliación" type="file" accept="application/json,.json" disabled={busy||preview?.aplicado} onChange={async e=>{setPreview(null);setChecked(false);setSource(null);setError("");try {const file=e.target.files?.[0];if(!file)return;if(file.size>250000)throw new Error("Archivo demasiado grande.");setSource(JSON.parse(await file.text()));}catch{setError("El archivo no es una conciliación JSON válida.");}}}/></label><Button disabled={!source||busy||preview?.aplicado} onClick={()=>submit()}>Previsualizar conciliación</Button>{error&&<p role="alert" className="text-[var(--fp-danger)]">{error}</p>}</Card>
 {preview&&<Card className="grid gap-4 p-5"><h2 className="text-xl font-bold">{preview.aplicado?"Conciliación aplicada":"Revisar conciliación"} · {preview.cliente}</h2><p>{preview.documento} · {preview.folio}</p><p>Fuente: {preview.fuente}</p><p>Historial anterior: {preview.abonosAnteriores.length} abonos por {money(preview.abonosAnteriores.reduce((n,p)=>n+p.valor,0))}. Historial documentado: {preview.abonosNuevos.length} abonos por {money(preview.abonosNuevos.reduce((n,p)=>n+p.total,0))}.</p><p>Capital pendiente: <strong>{money(preview.saldoCapital)}</strong> · Saldo de cuotas futuras: <strong>{money(preview.saldoPendiente)}</strong></p><DataTable><table className="w-full text-sm"><thead><tr>{["Comprobante","Fecha","Valor","Capital","Interés","Mora","Otros","Seguro"].map(h=><th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{preview.abonosNuevos.map(p=><tr key={p.documento}><td className="p-2">{p.documento}</td><td className="p-2">{p.fecha}</td>{[p.total,p.capital,p.interes,p.mora,p.otros,p.seguro].map((n,i)=><td key={i} className="p-2">{money(n)}</td>)}</tr>)}</tbody></table></DataTable><DataTable><table className="w-full text-sm"><thead><tr>{["Cuota","Vencimiento","Valor programado","Pagado al corte","Saldo capital"].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{preview.cuotas.map(r=><tr key={r.numero}><td className="p-2">{r.numero}</td><td className="p-2">{r.fechaVencimiento}</td>{[r.valorProgramado,r.valorAbonadoAlCorte,r.saldoCapital].map((n,i)=><td key={i} className="p-2">{money(n)}</td>)}</tr>)}</tbody></table></DataTable>{preview.aplicado?<a href={`/dashboard/abonos?search=${encodeURIComponent(preview.documento)}&selected=${id}`} className="fp-ui-button is-primary">Ver crédito conciliado</a>:<><label className="flex gap-2"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Verifiqué la identidad, los pagos y las cuotas contra el documento de origen.</label><Button disabled={busy||!checked} onClick={()=>submit(true)}>Confirmar conciliación histórica</Button></>}</Card>}
 </>;
}
